[package]
name = "test_with_bashunit"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://mush.javanile.org/manifest.html

[dependencies]
bashunit = "git https://github.com/TypedDevs/bashunit.git main"
