on:
  workflow_dispatch:

name: "autobuild"
permissions: {}

jobs:
  build:
    name: ShellCheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        public_copy:
          - https://raw.githubusercontent.com/javanile/mush/main/bin/mush
    steps:
      - uses: actions/checkout@v4
      - run: curl -sL ${{ matrix.public_copy }} > /usr/local/bin/mush && chmod +x /usr/local/bin/mush && mush --version
      - run: /usr/local/bin/mush build
      - run: /usr/local/bin/mush build --release
