on:
  push:
    branches:
      - main
  workflow_dispatch:

name: "shellcheck"
permissions: {}

jobs:
  shellcheck:
    if: contains(github.event.head_commit.message, 'shellcheck')
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
